version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123987
      - MYSQL_DATABASE=funcionarios_bd
    ports:
      - "3306:3306"
    networks:
      - production-network

  app-back:
    build:
      context: ./funcionarios-back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - production-network

  web-front:
      build:
        context: ./funcionarios-front-end
        dockerfile: Dockerfile
      stdin_open: true
      tty: true
      ports: 
          - "8081:8080"


networks:
  production-network:
    driver: bridge